
create table task_categories (category_id bigint generated by default as identity, category_description varchar(500) not null, category_name varchar(100) not null, primary key (category_id));
create table tasks (task_id bigint generated by default as identity, deadline timestamp, task_description varchar(100) not null, task_name varchar(100) not null, category_id bigint, primary key (task_id));
alter table tasks add constraint FK42ldd63quus0efpi2ec64q0qg foreign key (category_id) references task_categories;
